<template>
    <div class="categroy">
        <div class="c-service">
            <dl class="clear-fixed">
                <dt>分类</dt>
                <dt class="all">全部</dt>
                <dd>
                    <p-selector 
                    v-for="(ele,i) in menulist" 
                    :key="i" :title="ele.title" 
                    :sublist="ele.sub_list" 
                    :class="'name'+i" 
                    />
                </dd>
            </dl>
             <dl class="clear-fixed">
                <dt>区域</dt>
                <dt class="all">全部</dt>
                <dd>
                    <p-selector v-for="(ele,i) in menulist" :key="i" :title="ele.title" :sublist="ele.sub_list"/>
                </dd>
            </dl>
        </div>
        <!-- <div class="c-area">
            区域划分
        </div> -->
    </div>
</template>
<script>
import pSelector from './pSelect';
export default {
    components:{
        pSelector,
    },
    data(){
        return {
            menulist:[
              
                {
                    title:"美食",
                    type:"taste_food",
                     sub_list:[
                        {
                            name:"全部",
                            id:"all"
                        },
                        {
                            name:"更多地方菜",
                            id:"more_dish"
                        },
                        {
                            name:"烤肉",
                            id:"bubicue"
                        },
                        {
                            name:"食品保健",
                            id:"food_heanthy"
                        },
                        {
                            name:"特色菜",
                            id:"special_dish"
                        },
                        {
                            name:"日本菜",
                            id:"japan"
                        },
                        {
                            name:"饮品店",
                            id:"juice_shop"
                        },
                        {
                            name:"面包甜点",
                            id:"bread_taste"
                        },
                        {
                            name:"生日蛋糕",
                            id:"birthday_cake"
                        },
                        {
                            name:"火锅",
                            id:"hoppot"
                        },
                        {
                            name:"自助餐",
                            id:"self_food"
                        },
                        {
                            name:"小吃",
                            id:"sneck"
                        },
                        {
                            name:"快餐",
                            id:"fastfoot"
                        },
                        {
                            name:"日韩料理",
                            id:"japan_kairean"
                        },
                        {
                            name:"西餐",
                            id:"west_food"
                        },
                        {
                            name:"聚餐宴请",
                            id:"together_food"
                        },
                    ]
                },
                {
                    title:"酒店住宿",
                    "id":"hotel_host",
                    sub_list:[
                        {
                            name:"全部",
                            id:"all"
                        },
                        {
                            name:"更多地方菜",
                            id:"more_dish"
                        },
                        {
                            name:"烤肉",
                            id:"bubicue"
                        },
                        {
                            name:"食品保健",
                            id:"food_heanthy"
                        },
                        {
                            name:"特色菜",
                            id:"special_dish"
                        },
                        {
                            name:"日本菜",
                            id:"japan"
                        },
                        {
                            name:"饮品店",
                            id:"juice_shop"
                        },
                        {
                            name:"面包甜点",
                            id:"bread_taste"
                        },
                        {
                            name:"生日蛋糕",
                            id:"birthday_cake"
                        },
                        {
                            name:"火锅",
                            id:"hoppot"
                        },
                        {
                            name:"自助餐",
                            id:"self_food"
                        },
                        {
                            name:"小吃",
                            id:"sneck"
                        },
                        {
                            name:"快餐",
                            id:"fastfoot"
                        },
                        {
                            name:"日韩料理",
                            id:"japan_kairean"
                        },
                        {
                            name:"西餐",
                            id:"west_food"
                        },
                        {
                            name:"聚餐宴请",
                            id:"together_food"
                        },
                    ]
                },
                {
                    title:"休闲娱乐",
                    type:"spane_paly",
                    sub_list:[
                        {
                            name:"全部",
                            id:"all"
                        },
                        {
                            name:"更多地方菜",
                            id:"more_dish"
                        },
                        {
                            name:"烤肉",
                            id:"bubicue"
                        },
                        {
                            name:"食品保健",
                            id:"food_heanthy"
                        },
                        {
                            name:"特色菜",
                            id:"special_dish"
                        },
                        {
                            name:"日本菜",
                            id:"japan"
                        },
                        {
                            name:"饮品店",
                            id:"juice_shop"
                        },
                        {
                            name:"面包甜点",
                            id:"bread_taste"
                        },
                        {
                            name:"生日蛋糕",
                            id:"birthday_cake"
                        },
                        {
                            name:"火锅",
                            id:"hoppot"
                        },
                        {
                            name:"自助餐",
                            id:"self_food"
                        },
                        {
                            name:"小吃",
                            id:"sneck"
                        },
                        {
                            name:"快餐",
                            id:"fastfoot"
                        },
                        {
                            name:"日韩料理",
                            id:"japan_kairean"
                        },
                        {
                            name:"西餐",
                            id:"west_food"
                        },
                        {
                            name:"聚餐宴请",
                            id:"together_food"
                        },
                    ]
                },
                {
                    title:"生活服务",
                    type:"life_serve",
                    sub_list:[
                        {
                            name:"全部",
                            id:"all"
                        },
                        {
                            name:"更多地方菜",
                            id:"more_dish"
                        },
                        {
                            name:"烤肉",
                            id:"bubicue"
                        },
                        {
                            name:"食品保健",
                            id:"food_heanthy"
                        },
                        {
                            name:"特色菜",
                            id:"special_dish"
                        },
                        {
                            name:"日本菜",
                            id:"japan"
                        },
                        {
                            name:"饮品店",
                            id:"juice_shop"
                        },
                        {
                            name:"面包甜点",
                            id:"bread_taste"
                        },
                        {
                            name:"生日蛋糕",
                            id:"birthday_cake"
                        },
                        {
                            name:"火锅",
                            id:"hoppot"
                        },
                        {
                            name:"自助餐",
                            id:"self_food"
                        },
                        {
                            name:"小吃",
                            id:"sneck"
                        },
                        {
                            name:"快餐",
                            id:"fastfoot"
                        },
                        {
                            name:"日韩料理",
                            id:"japan_kairean"
                        },
                        {
                            name:"西餐",
                            id:"west_food"
                        },
                        {
                            name:"聚餐宴请",
                            id:"together_food"
                        },
                    ]
                },
                {
                    title:"宴会",
                    type:"party",
                    sub_list:[
                        {
                            name:"全部",
                            id:"all"
                        },
                        {
                            name:"更多地方菜",
                            id:"more_dish"
                        },
                        {
                            name:"烤肉",
                            id:"bubicue"
                        },
                        {
                            name:"食品保健",
                            id:"food_heanthy"
                        },
                        {
                            name:"特色菜",
                            id:"special_dish"
                        },
                        {
                            name:"日本菜",
                            id:"japan"
                        },
                        {
                            name:"饮品店",
                            id:"juice_shop"
                        },
                        {
                            name:"面包甜点",
                            id:"bread_taste"
                        },
                        {
                            name:"生日蛋糕",
                            id:"birthday_cake"
                        },
                        {
                            name:"火锅",
                            id:"hoppot"
                        },
                        {
                            name:"自助餐",
                            id:"self_food"
                        },
                        {
                            name:"小吃",
                            id:"sneck"
                        },
                        {
                            name:"快餐",
                            id:"fastfoot"
                        },
                        {
                            name:"日韩料理",
                            id:"japan_kairean"
                        },
                        {
                            name:"西餐",
                            id:"west_food"
                        },
                        {
                            name:"聚餐宴请",
                            id:"together_food"
                        },
                    ]
                },
                 {
                    title:"时尚购",
                    type:"fashion_shopping",
                    sub_list:[
                        {
                            name:"全部",
                            id:"all"
                        },
                        {
                            name:"更多地方菜",
                            id:"more_dish"
                        },
                        {
                            name:"烤肉",
                            id:"bubicue"
                        },
                        {
                            name:"食品保健",
                            id:"food_heanthy"
                        },
                        {
                            name:"特色菜",
                            id:"special_dish"
                        },
                        {
                            name:"日本菜",
                            id:"japan"
                        },
                        {
                            name:"饮品店",
                            id:"juice_shop"
                        },
                        {
                            name:"面包甜点",
                            id:"bread_taste"
                        },
                        {
                            name:"生日蛋糕",
                            id:"birthday_cake"
                        },
                        {
                            name:"火锅",
                            id:"hoppot"
                        },
                        {
                            name:"自助餐",
                            id:"self_food"
                        },
                        {
                            name:"小吃",
                            id:"sneck"
                        },
                        {
                            name:"快餐",
                            id:"fastfoot"
                        },
                        {
                            name:"日韩料理",
                            id:"japan_kairean"
                        },
                        {
                            name:"西餐",
                            id:"west_food"
                        },
                        {
                            name:"聚餐宴请",
                            id:"together_food"
                        },
                    ]
                },
                 {
                    title:"母婴亲子",
                    type:"mom_child",
                    sub_list:[
                        {
                            name:"全部",
                            id:"all"
                        },
                        {
                            name:"更多地方菜",
                            id:"more_dish"
                        },
                        {
                            name:"烤肉",
                            id:"bubicue"
                        },
                        {
                            name:"食品保健",
                            id:"food_heanthy"
                        },
                        {
                            name:"特色菜",
                            id:"special_dish"
                        },
                        {
                            name:"日本菜",
                            id:"japan"
                        },
                        {
                            name:"饮品店",
                            id:"juice_shop"
                        },
                        {
                            name:"面包甜点",
                            id:"bread_taste"
                        },
                        {
                            name:"生日蛋糕",
                            id:"birthday_cake"
                        },
                        {
                            name:"火锅",
                            id:"hoppot"
                        },
                        {
                            name:"自助餐",
                            id:"self_food"
                        },
                        {
                            name:"小吃",
                            id:"sneck"
                        },
                        {
                            name:"快餐",
                            id:"fastfoot"
                        },
                        {
                            name:"日韩料理",
                            id:"japan_kairean"
                        },
                        {
                            name:"西餐",
                            id:"west_food"
                        },
                        {
                            name:"聚餐宴请",
                            id:"together_food"
                        },
                    ]
                },
                 {
                    title:"宠物",
                    type:"pet",
                    sub_list:[
                        {
                            name:"全部",
                            id:"all"
                        },
                        {
                            name:"更多地方菜",
                            id:"more_dish"
                        },
                        {
                            name:"烤肉",
                            id:"bubicue"
                        },
                        {
                            name:"食品保健",
                            id:"food_heanthy"
                        },
                        {
                            name:"特色菜",
                            id:"special_dish"
                        },
                        {
                            name:"日本菜",
                            id:"japan"
                        },
                        {
                            name:"饮品店",
                            id:"juice_shop"
                        },
                        {
                            name:"面包甜点",
                            id:"bread_taste"
                        },
                        {
                            name:"生日蛋糕",
                            id:"birthday_cake"
                        },
                        {
                            name:"火锅",
                            id:"hoppot"
                        },
                        {
                            name:"自助餐",
                            id:"self_food"
                        },
                        {
                            name:"小吃",
                            id:"sneck"
                        },
                        {
                            name:"快餐",
                            id:"fastfoot"
                        },
                        {
                            name:"日韩料理",
                            id:"japan_kairean"
                        },
                        {
                            name:"西餐",
                            id:"west_food"
                        },
                        {
                            name:"聚餐宴请",
                            id:"together_food"
                        },
                    ]
                },
                 {
                    title:"汽车服务",
                    type:"car_service",
                    sub_list:[
                        {
                            name:"全部",
                            id:"all"
                        },
                        {
                            name:"更多地方菜",
                            id:"more_dish"
                        },
                        {
                            name:"烤肉",
                            id:"bubicue"
                        },
                        {
                            name:"食品保健",
                            id:"food_heanthy"
                        },
                        {
                            name:"特色菜",
                            id:"special_dish"
                        },
                        {
                            name:"日本菜",
                            id:"japan"
                        },
                        {
                            name:"饮品店",
                            id:"juice_shop"
                        },
                        {
                            name:"面包甜点",
                            id:"bread_taste"
                        },
                        {
                            name:"生日蛋糕",
                            id:"birthday_cake"
                        },
                        {
                            name:"火锅",
                            id:"hoppot"
                        },
                        {
                            name:"自助餐",
                            id:"self_food"
                        },
                        {
                            name:"小吃",
                            id:"sneck"
                        },
                        {
                            name:"快餐",
                            id:"fastfoot"
                        },
                        {
                            name:"日韩料理",
                            id:"japan_kairean"
                        },
                        {
                            name:"西餐",
                            id:"west_food"
                        },
                        {
                            name:"聚餐宴请",
                            id:"together_food"
                        },
                    ]
                },
                 {
                    title:"家装",
                    type:"family_decoration",
                    sub_list:[

                    ]
                },
                 {
                    title:"结婚",
                    type:"merried"
                },
                //  {
                //     "name":"",
                //     "id":""
                // },
            ],
            areaList:[
                 {
                    "name":"",
                    "id":""
                }, 
                {
                    "name":"",
                    "id":""
                },
            ]
        }
    },
   
}
</script>